const router = require('express').Router();
const { protect, authorize } = require('../middleware/auth');
const C = require('../controllers/adminWorkspace.controller');
router.use(protect, authorize('admin', 'super_admin'));
router.get('/me', C.me);
router.get('/summary', C.summary);
router.get('/users', C.users);
router.get('/users/:id', C.user);
router.get('/users/:id/activity', C.activity);
router.patch('/users/:id/access', C.changeAccess);
router.post('/users/:id/adjustments', C.adjust);
router.get('/jobs', C.jobs);
router.patch('/jobs/:id/status', C.jobStatus);
router.get('/applications', C.applications);
router.get('/payments', C.payments);
router.get('/invoices', C.invoices);
router.get('/audit', C.auditLogs);
router.use(authorize('super_admin'));
router.get('/staff', C.staff);
router.post('/staff', C.createStaff);
router.patch('/users/:id/role', C.changeRole);
router.get('/plans', C.plans);
router.patch('/plans/:id', C.updatePlan);
router.get('/flags', C.flags);
router.patch('/flags/:key', C.updateFlag);
router.get('/infrastructure', C.infrastructure);
module.exports = router;
