const router = require('express').Router()
const c = require('../controllers/admin.controller')
const { protect, authorize } = require('../middleware/auth')
router.use(protect, authorize('admin', 'super_admin'))
router.use('/campaigns', require('./bulkEmailCampaign.routes'))
router.get('/stats', c.getStats)
router.get('/jobs', c.getAllJobs)
router.put('/jobs/:id/status', c.updateJobStatus)
router.get('/users', c.getAllUsers)
router.put('/users/:id/toggle', c.toggleUserActive)
router.put('/users/:id/role', authorize('super_admin'), c.updateUserRole)
module.exports = router
