const router = require('express').Router()
const { protect, authorize } = require('../middleware/auth')
const c = require('../controllers/bulkEmailCampaign.controller')
router.use(protect, authorize('employer', 'admin', 'super_admin'))
router.get('/templates', c.getTemplates)
router.post('/', c.createCampaign)
router.get('/', c.getMyCampaigns)
router.get('/jobs/:jobId/shortlisted-candidates', c.getShortlistedCandidatesForJob)
router.get('/jobs/:jobId/candidates', c.getCandidatesForJobByStatus)
router.post('/:id/send', c.sendCampaign)
module.exports = router
