const router = require('express').Router()
const { protect, authorize } = require('../middleware/auth')
const c = require('../controllers/referral.controller')
router.use(protect)
router.use('/payouts', require('./phase2Payout.routes'))
router.get('/code', authorize('candidate'), c.getMyReferralCode)
router.get('/my', authorize('candidate'), c.getMyReferrals)
router.get('/points', authorize('candidate'), c.getMyLoyaltyPoints)
router.get('/loyalty-points', authorize('candidate'), c.getMyLoyaltyPoints)
router.get('/employer/tracking', authorize('employer', 'admin', 'super_admin'), c.getEmployerReferrals)
router.get('/employer', authorize('employer', 'admin', 'super_admin'), c.getEmployerReferrals)
router.get('/admin', authorize('admin', 'super_admin'), c.getAdminReferrals)
router.post('/applications/:applicationId/award', authorize('admin', 'super_admin'), c.awardReferralPoints)
router.post('/:applicationId/award-points', authorize('admin', 'super_admin'), c.awardReferralPoints)
router.post('/', authorize('candidate', 'employer', 'admin', 'super_admin'), c.createReferral)
router.get('/:id', authorize('candidate', 'employer', 'admin', 'super_admin'), c.getReferralById)
module.exports = router
