'use client'
import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import { adminRequest, mutation } from '@/lib/adminApi'
import { AdminFrame, Notice, Pages, RecordFields, useStaff, fieldStyle, primaryStyle, secondaryStyle, label } from './AdminShell'
import NotesPanel from './NotesPanel'
export default function AdminUserDetail() {
  const { id } = useParams<{ id: string }>(), staff = useStaff()
  const [record, setRecord] = useState<any>(null), [activity, setActivity] = useState<any[]>([]), [tab, setTab] = useState('payments'), [page, setPage] = useState(1), [pagination, setPagination] = useState<any>(), [error, setError] = useState(''), [success, setSuccess] = useState(''), [busy, setBusy] = useState(false)
  const [why, setWhy] = useState(''), [nextRole, setNextRole] = useState(''), [points, setPoints] = useState(0), [plans, setPlans] = useState<any[]>([]), [plan, setPlan] = useState('standard'), [days, setDays] = useState(30)
  const load = async () => { const result = await adminRequest(`/admin/workspace/users/${id}`); setRecord(result.data); setNextRole(result.data.user.role); if (record?.user.role !== result.data.user.role) { setTab('payments'); setPage(1) } }
  useEffect(() => { let cancelled = false; setRecord(null); adminRequest(`/admin/workspace/users/${id}`).then(result => { if (!cancelled) { setRecord(result.data); setNextRole(result.data.user.role); setTab(['candidate', 'employer'].includes(result.data.user.role) ? 'applications' : 'payments'); setPage(1) } }).catch(err => { if (!cancelled) setError(err.message) }); return () => { cancelled = true } }, [id])
  useEffect(() => { if (staff.role === 'super_admin') adminRequest('/admin/workspace/plans').then(result => setPlans(result.data)).catch(err => setError(err.message)) }, [staff.role])
  useEffect(() => { if (!record) return; let cancelled = false; setActivity([]); setPagination(undefined); adminRequest(`/admin/workspace/users/${id}/activity?type=${tab}&page=${page}`).then(result => { if (!cancelled) { setActivity(result.data); setPagination(result.pagination) } }).catch(err => { if (!cancelled) setError(err.message) }); return () => { cancelled = true } }, [id, tab, page, record])
  async function change(path: string, body: unknown) { setBusy(true); setError(''); setSuccess(''); try { await adminRequest(path, mutation(path.endsWith('adjustments') ? 'POST' : 'PATCH', body)); await load(); setWhy(''); setSuccess('Change saved and recorded in the audit log.') } catch (err) { setError((err as Error).message) } finally { setBusy(false) } }
  if (!record) return <AdminFrame title="User details"><Notice error={error} />{!error && <p>Loading profile…</p>}</AdminFrame>
  const { user, profile, loyaltyBalance } = record, candidate = user.role === 'candidate', employer = user.role === 'employer'
  const tabs = candidate ? ['applications', 'resumes', 'training', 'classes', 'deployments', 'attendance', 'payrolls', 'invoices', 'loyalty', 'payments'] : employer ? ['jobs', 'applications', 'payments', 'invoices', 'deployments', 'attendance', 'payrolls', 'contracts', 'manpower', 'campaigns'] : ['payments']
  const canAccess = staff.role === 'super_admin' || ['candidate', 'employer', 'trainer'].includes(user.role)
  return <AdminFrame title={user.email} description="Review the profile, related activity and private staff notes."><Notice error={error} success={success} /><div className="grid items-start gap-5 lg:grid-cols-3"><div className="space-y-5 lg:col-span-2"><section className="rounded-xl border bg-white p-5"><h2 className="mb-4 text-xl font-semibold">Account</h2><RecordFields data={user} /></section><section className="rounded-xl border bg-white p-5"><h2 className="mb-4 text-xl font-semibold">{employer ? 'Company profile' : candidate ? 'Candidate profile' : 'Profile'}</h2>{profile ? <RecordFields data={profile} /> : <p>No profile has been created.</p>}{candidate && <p className="mt-4 font-semibold">Loyalty balance: {loyaltyBalance}</p>}</section>
      <section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Activity history</h2><div className="my-4 flex flex-wrap gap-2">{tabs.map(value => <button key={value} onClick={() => { setTab(value); setPage(1) }} className={value === tab ? primaryStyle : secondaryStyle}>{label(value)}</button>)}</div><Pages pagination={pagination} onPage={setPage} />{!activity.length && <p className="text-slate-500">No records on this page.</p>}<div className="space-y-3">{activity.map(item => <details key={item.id} className="rounded-lg border p-4"><summary className="cursor-pointer font-medium">{item.title || item.training?.title || item.job?.title || item.invoiceNumber || item.planName || item.reason || item.id} {item.status && `· ${item.status}`}</summary><div className="mt-4"><RecordFields data={item} /></div></details>)}</div></section>
      <NotesPanel key={id} entityType={candidate ? 'candidate' : employer ? 'employer' : 'user'} entityId={id} />
    </div><aside className="space-y-5"><section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Support actions</h2><label className="my-3 block">Reason for change<textarea required minLength={5} maxLength={500} className={`${fieldStyle} mt-1`} value={why} onChange={event => setWhy(event.target.value)} /></label>
      {canAccess && user.id !== staff.id && <button disabled={busy || why.trim().length < 5} className={secondaryStyle} onClick={() => change(`/admin/workspace/users/${id}/access`, { isActive: !user.isActive, reason: why })}>{user.isActive ? 'Deactivate account' : 'Activate account'}</button>}
      {staff.role === 'super_admin' && <div className="my-4 space-y-2"><label>Role<select className={fieldStyle} value={nextRole} onChange={event => setNextRole(event.target.value)}>{['candidate', 'employer', 'trainer', 'admin', 'super_admin'].map(value => <option key={value}>{value}</option>)}</select></label><button disabled={busy || why.trim().length < 5 || nextRole === user.role} className={primaryStyle} onClick={() => change(`/admin/workspace/users/${id}/role`, { role: nextRole, reason: why })}>Update role</button></div>}
      {candidate && <div className="my-4 space-y-2"><label>Point adjustment<input className={fieldStyle} type="number" min={-1000} max={1000} step={1} value={points} onChange={event => setPoints(Number(event.target.value))} /></label><button disabled={busy || !points || why.trim().length < 5} className={primaryStyle} onClick={() => change(`/admin/workspace/users/${id}/adjustments`, { kind: 'loyalty', points, reason: why })}>Adjust loyalty points</button></div>}
      {employer && profile && <button className={`${secondaryStyle} my-3`} disabled={busy || why.trim().length < 5} onClick={() => change(`/admin/workspace/users/${id}/adjustments`, { kind: 'employer_verification', isVerified: !profile.isVerified, reason: why })}>{profile.isVerified ? 'Remove company verification' : 'Verify company'}</button>}
      {employer && staff.role === 'super_admin' && <div className="space-y-3 border-t pt-4"><p className="text-sm text-slate-600">Manual access grants are audited and do not create payment receipts.</p><label>Subscription plan<select className={fieldStyle} value={plan} onChange={event => setPlan(event.target.value)}>{plans.filter(item => item.isActive).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Days of access<input className={fieldStyle} type="number" min={1} max={365} value={days} onChange={event => setDays(Number(event.target.value))} /></label><button disabled={busy || why.trim().length < 5} className={primaryStyle} onClick={() => change(`/admin/workspace/users/${id}/adjustments`, { kind: 'subscription', plan, days, reason: why })}>Apply subscription adjustment</button></div>}
    </section><Link className="block rounded-xl border bg-white p-4 text-blue-700" href={`/admin/communication?entityType=${candidate ? 'candidate' : employer ? 'employer' : 'user'}&entityId=${id}`}>Open a support ticket for this record →</Link></aside></div></AdminFrame>
}
