'use client'
import { useEffect, useState } from 'react'
import { adminRequest, mutation } from '@/lib/adminApi'
import { fieldStyle, primaryStyle, secondaryStyle, Pages, Notice, useStaff } from './AdminShell'
export default function NotesPanel({ entityType, entityId }: { entityType: string; entityId: string }) {
  const staff = useStaff(), [notes, setNotes] = useState<any[]>([]), [body, setBody] = useState(''), [page, setPage] = useState(1), [pagination, setPagination] = useState<any>(), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const load = async () => { const result = await adminRequest(`/internal/notes/${entityType}/${entityId}?page=${page}`); setNotes(result.data); setPagination(result.pagination) }
  useEffect(() => { let cancelled = false; setNotes([]); adminRequest(`/internal/notes/${entityType}/${entityId}?page=${page}`).then(result => { if (!cancelled) { setNotes(result.data); setPagination(result.pagination); setError('') } }).catch(err => { if (!cancelled) setError(err.message) }); return () => { cancelled = true } }, [entityType, entityId, page])
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await adminRequest('/internal/notes', mutation('POST', { entityType, entityId, body })); setBody(''); if (page === 1) await load(); else setPage(1) } catch (err) { setError((err as Error).message) } finally { setBusy(false) } }
  const remove = async (note: any) => { if (!window.confirm('Delete this internal note? The deletion will be recorded in the audit log.')) return; setBusy(true); setError(''); try { await adminRequest(`/internal/notes/${note.id}`, { method: 'DELETE' }); await load() } catch (err) { setError((err as Error).message) } finally { setBusy(false) } }
  return <section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Internal notes</h2><p className="my-2 text-sm text-slate-600">Visible only to admin staff. Use notes to coordinate support for this record.</p><Notice error={error} /><form onSubmit={save} className="my-4 space-y-3"><label className="block">New note<textarea required maxLength={10000} className={`${fieldStyle} mt-1`} value={body} onChange={event => setBody(event.target.value)} /></label><button disabled={busy} className={primaryStyle}>Add note</button></form>{!notes.length && <p className="text-sm text-slate-500">No notes on this page.</p>}<div className="space-y-3">{notes.map(note => <article key={note.id} className="rounded-lg bg-slate-50 p-3"><p className="whitespace-pre-wrap break-words">{note.body}</p><p className="my-2 text-xs text-slate-500">{note.author?.email || 'Staff'} · {new Date(note.createdAt).toLocaleString()}</p>{(note.authorId === staff.id || staff.role === 'super_admin') && <button disabled={busy} className={secondaryStyle} onClick={() => remove(note)}>Delete my note</button>}</article>)}</div><Pages pagination={pagination} onPage={setPage} busy={busy} /></section>
}
