'use client'
import { tr, useLocale } from '@/lib/localization'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { adminRequest, mutation } from '@/lib/adminApi'
import { AdminFrame, Notice, Pages, fieldStyle, primaryStyle } from './AdminShell'
export default function StaffManager() {
  useLocale()

  const [staff, setStaff] = useState<any[]>([]), [page, setPage] = useState(1), [pagination, setPagination] = useState<any>(), [error, setError] = useState(''), [success, setSuccess] = useState(''), [busy, setBusy] = useState(false)
  const [form, setForm] = useState({ email: '', password: '', role: 'admin', reason: '' })
  const load = async () => { const result = await adminRequest(`/admin/workspace/staff?page=${page}`); setStaff(result.data); setPagination(result.pagination) }
  useEffect(() => { load().catch(err => setError(err.message)) }, [page])
  const create = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); setSuccess(''); try { await adminRequest('/admin/workspace/staff', mutation('POST', form)); setForm({ email: '', password: '', role: 'admin', reason: '' }); setSuccess('Staff account created. Provide the initial password directly to the staff member.'); await load() } catch (err) { setError((err as Error).message) } finally { setBusy(false) } }
  return <AdminFrame title={tr("Staff & roles")} description={tr("Super admin controls team access. Role and activation changes are audited.")}><Notice error={error} success={success} /><section className="mb-6 rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">{tr("Create an internal staff account")}</h2><form onSubmit={create} className="mt-4 grid gap-3 sm:grid-cols-2"><label>{tr("Email")}<input required type="email" className={fieldStyle} value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></label><label>{tr("Initial password")}<input required type="password" autoComplete="new-password" minLength={12} maxLength={128} className={fieldStyle} value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /></label><label>{tr("Role")}<select className={fieldStyle} value={form.role} onChange={event => setForm({ ...form, role: event.target.value })}><option value="admin">{tr("Internal admin")}</option><option value="super_admin">{tr("Super admin")}</option></select></label><label>{tr("Reason")}<input required minLength={5} maxLength={500} className={fieldStyle} value={form.reason} onChange={event => setForm({ ...form, reason: event.target.value })} /></label><div><button disabled={busy} className={primaryStyle}>{tr("Create staff account")}</button></div></form></section><section className="mb-6 rounded-xl border bg-white p-5"><h2 className="font-semibold">{tr("Access levels")}</h2><p className="mt-2 text-sm">{tr("Internal admin: candidate/employer visibility, moderation, support, loyalty adjustments, company verification and audits.")}</p><p className="mt-2 text-sm">{tr("Super admin: all admin tools, staff roles, plans, subscription adjustments, feature flags and infrastructure health.")}</p><p className="mt-2 text-sm">{tr("Trainer: training modules only. Create trainer accounts from Training & Classes.")}</p></section><Pages pagination={pagination} onPage={setPage} busy={busy} /><div className="space-y-3">{staff.map(user => <article key={user.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-4"><div><h2 className="font-semibold">{user.email}</h2><p className="text-sm">{user.role} · {tr(user.isActive ? 'Active' : 'Inactive')}</p></div><Link href={`/admin/users/${user.id}`} className="text-blue-700 underline">{tr("Manage access & role")}</Link></article>)}</div></AdminFrame>
}
