'use client'
import { useEffect, useState } from 'react'
import { adminRequest, mutation } from '@/lib/adminApi'
import { AdminFrame, Notice, RecordFields, fieldStyle, primaryStyle, secondaryStyle } from './AdminShell'
export default function SystemSettings({ kind }: { kind: 'plans' | 'flags' | 'infrastructure' }) {
  const [rows, setRows] = useState<any[]>([]), [infrastructure, setInfrastructure] = useState<any>(), [error, setError] = useState(''), [success, setSuccess] = useState(''), [busy, setBusy] = useState(false), [reasons, setReasons] = useState<Record<string, string>>({})
  const load = async () => { const result = await adminRequest(`/admin/workspace/${kind}`); if (kind === 'infrastructure') setInfrastructure(result.data); else setRows(result.data) }
  useEffect(() => { load().catch(err => setError(err.message)) }, [kind])
  const save = async (row: any) => {
    setBusy(true); setError(''); setSuccess('')
    try { const body = kind === 'plans' ? { name: row.name, amountPaise: Math.round(Number(row.priceRupees ?? row.amountPaise / 100) * 100), durationDays: Number(row.durationDays), features: String(row.featureText ?? row.features.join('\n')).split('\n').map(value => value.trim()).filter(Boolean), isActive: row.isActive, reason: reasons[row.id] } : { enabled: !row.enabled, reason: reasons[row.key] }; await adminRequest(`/admin/workspace/${kind}/${row.id || row.key}`, mutation('PATCH', body)); setSuccess('Settings saved and recorded in the audit log.'); setReasons({}); await load() }
    catch (err) { setError((err as Error).message) } finally { setBusy(false) }
  }
  const edit = (index: number, changes: any) => setRows(rows.map((row, i) => i === index ? { ...row, ...changes } : row))
  const title = kind === 'plans' ? 'Plans & perks' : kind === 'flags' ? 'Feature flags' : 'Infrastructure health'
  return <AdminFrame title={title} description={kind === 'plans' ? 'Prices, durations and displayed perks apply to new orders. Existing orders keep their saved purchase terms.' : kind === 'flags' ? 'Switch modules off for portal users while admins retain management access.' : 'Inspect runtime health and integration configuration without exposing credentials.'}><Notice error={error} success={success} />
    {kind === 'plans' && <p className="mb-5 rounded-lg bg-blue-50 p-4 text-sm">Plan IDs stay fixed to support existing subscriptions. Perks describe the plan; entitlement rules retain their current behavior. Configure each price in rupees. Deactivating a plan prevents new purchases.</p>}
    {kind === 'infrastructure' && <section className="rounded-xl border bg-white p-5"><button className={`${secondaryStyle} mb-5`} onClick={() => { setError(''); load().catch(err => setError(err.message)) }}>Refresh health</button>{infrastructure ? <RecordFields data={infrastructure} /> : !error && <p>Checking services…</p>}<p className="mt-5 text-sm text-slate-600">Integration checks show whether credentials are configured. Actual email delivery, payment processing and media uploads must be tested with their providers. Hosting configuration is managed outside this portal.</p></section>}
    <div className="grid gap-5 md:grid-cols-2">{rows.map((row, index) => <section key={row.id || row.key} className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">{row.name || row.key}</h2>{kind === 'plans' ? <form onSubmit={event => { event.preventDefault(); save(row) }} className="mt-4 space-y-3"><label className="block">Name<input required maxLength={100} className={fieldStyle} value={row.name} onChange={event => edit(index, { name: event.target.value })} /></label><label className="block">Price (₹)<input required type="number" step="0.01" min={row.id === 'free' ? 0 : 1} max={1000000} readOnly={row.id === 'free'} className={fieldStyle} value={row.priceRupees ?? row.amountPaise / 100} onChange={event => edit(index, { priceRupees: event.target.value })} /></label><label className="block">Duration (days)<input required type="number" min={1} max={365} className={fieldStyle} value={row.durationDays} onChange={event => edit(index, { durationDays: event.target.value })} /></label><label className="block">Perks (one per line)<textarea className={fieldStyle} rows={7} value={row.featureText ?? row.features.join('\n')} onChange={event => edit(index, { featureText: event.target.value })} /></label><label className="block"><input type="checkbox" checked={row.isActive} onChange={event => edit(index, { isActive: event.target.checked })} /> Available for new subscriptions</label><label className="block">Reason<input required minLength={5} maxLength={500} className={fieldStyle} value={reasons[row.id] || ''} onChange={event => setReasons({ ...reasons, [row.id]: event.target.value })} /></label><button disabled={busy} className={primaryStyle}>Save plan</button></form> : <form onSubmit={event => { event.preventDefault(); save(row) }} className="mt-4 space-y-3"><p>{row.description}</p><p className={row.enabled ? 'text-green-800' : 'text-red-800'}>{row.enabled ? 'Enabled' : 'Disabled'}</p><label className="block">Reason<input required minLength={5} maxLength={500} className={fieldStyle} value={reasons[row.key] || ''} onChange={event => setReasons({ ...reasons, [row.key]: event.target.value })} /></label><button disabled={busy} className={primaryStyle}>{row.enabled ? 'Disable module' : 'Enable module'}</button></form>}</section>)}</div>
  </AdminFrame>
}
